server:
  port: 10010
spring:
  application:
    name: ly-gateway
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
zuul:
  prefix: /api # 添加路由前缀
  routes:
    item-service: /item/**    #商品微服务的映射路径
    search-service: /search/** #搜索微服务
    user-service: /user/** #用户微服务
ribbon:
  ConnectTimeout: 1000 # 连接超时时间(ms)
  ReadTimeout: 1000 # 通信超时时间(ms)
  OkToRetryOnAllOperations: true # 是否对所有操作重试
  MaxAutoRetries: 0 # 当前服务重试次数
  MaxAutoRetriesNextServer: 0 # 切换服务重试次数
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 5000 # 熔断超时时长：5000ms
